In [1]:
#Program to Perform Matrix Multiplication and Transformation Using Python
import numpy as np
a=np.array([[1,2,3],[1,2,4],[1,4,2]])
print("The Matrix a is : \n",a)

b=np.array([[3,1,3],[3,2,1],[4,1,2]])
print("\nThe Matrix b is : \n",b)
 
print("\nMultiplication of Matrix a and b is :\n",np.dot(a,b))

print("\nTranspose of Matrix b is :\n",b.transpose())

The Matrix a is : 
 [[1 2 3]
 [1 2 4]
 [1 4 2]]

The Matrix b is : 
 [[3 1 3]
 [3 2 1]
 [4 1 2]]

Multiplication of Matrix a and b is :
 [[21  8 11]
 [25  9 13]
 [23 11 11]]

Transpose of Matrix b is :
 [[3 3 4]
 [1 2 1]
 [3 1 2]]
