In [1]:
#Program to Perform svd Using Python
import numpy as np
from scipy.linalg import svd
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("The Matrix a is : \n",a)

v,s,t=svd(a) #to find svd
print("\n v = ",v)
print("\n s = ",s)
print("\n t = ",t)

e=(v @ np.diag(s) @t)
print("\n",e)

The Matrix a is : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

 v =  [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]

 s =  [1.68481034e+01 1.06836951e+00 4.41842475e-16]

 t =  [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]

 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
